server:
  port: 8085
  
spring:
  application:
    name: CONFIG-SERVER
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rajraushan18/microservice-config
          clone-on-start: true  #it will clone when it will start for the first time, then will not take long time
              